---
- name: Configure Nginx
  hosts: webserver
  become: yes

  vars:
    port: 80
    port_ssl: 443
    server_name: localhost
    root_path: /var/www/html

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy index.html
      template:
        src: index.html.j2
        dest: "{{ root_path }}/index.html"
        owner: root
        group: root
        mode: 0644
      
    - name: Deploy nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644
      notify: restart nginx
        - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Wait for nginx
      wait_for:
        port: "{{ port }}"
        state: started
        timeout: 30

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

