---
- name: Configure Nginx
  hosts: atonErmin
  become: yes

  vars:
    port: 80
    port_ssl: 443
    server_name: localhost
    root_path: /var/www/html
    index_text: Hello from ansible! Task 1
    ssl_key: ssl/selfsigned.key
    ssl_crt: ssl/selfsigned.crt
    ssl_dest: /etc/nginx/ssl

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create SSL directory
      file:
        path: "{{ ssl_dest }}"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Copy SSL certificate
      copy:
        src: "{{ ssl_crt }}"
        dest: "{{ ssl_dest }}/selfsigned.crt"
        owner: root
        group: root
        mode: "0644"

    - name: Copy SSL key
      copy:
        src: "{{ ssl_key }}"
        dest: "{{ ssl_dest }}/selfsigned.key"
        owner: root
        group: root
        mode: "0600"

    - name: Copy index.html
      template:
        src: index.html.j2
        dest: "{{ root_path }}/index.html"

    - name: Deploy nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Wait for nginx
      wait_for:
        port: "{{ port }}"
        state: started
        timeout: 30

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
